# (1): Specify analysis packages, specifically the Flutter linter we have:
include: package:flutter_lints/flutter.yaml

# (2): Configure the Flutter linter:
linter:

  # (2.1): Specify the rules for the linter --- these rules must exist in `package:flutter_lints/flutter.yaml`
  # :: the rules below hold globally; to ignore a file, use `// ignore_for_file: name_of_lint` 
  # :: a list of all available lint options is here: https://dart.dev/lints.
  # :: to learn more, read: https://dart.dev/guides/language/analysis-options
  rules:
    
    # (2.1.1): Do you want to avoid print?
    avoid_print: false

    # (2.1.2): Do you prefer... some complicated shit?
    prefer_const_constructors_in_immutables: false

    # (2.1.3): Do you like using const constructors?
    prefer_const_constructors: false

    # (2.1.4): ...
    prefer_const_literals_to_create_immutables: false

    # (2.1.5): ...
    prefer_final_fields: false

    # (2.1.6): ...
    unnecessary_breaks: true

    # (2.1.7): ...
    use_key_in_widget_constructors: false
