# (1): Specify the name of the application:
name: namer_app

# (2): Specify a description for the application:
description: "A new Flutter project."

# (3): I am not sure what this really does...
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# (4): Specify a version and build number via the syntax: version.num.ber+build.number
version: 1.0.0+1

# (5): Not sure what this is yet, but "SDK" from "Flutter SDK" is there:
environment:

  # (5.1): SDK version
  sdk: ^3.7.0

# (6): Specify the necessary dependencies:
# :: to update all dependencies, run `flutter pub upgrade --major-versions`
# :: to manually update dependencies, update them manually with desired version number
# :: to see which dependencies have new versions, run `flutter pub outdates`
dependencies:

  # (6.1): Flutter:
  flutter:

    # (6.1.1): SDK:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # (6.2): "Cupertino Icons" are basic icons that come with Flutter
  # :: to learn more, go to: https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html
  cupertino_icons: ^1.0.8

  # (6.3): Add the "english_words" dependency:
  english_words: ^4.0.0

  # (6.4): Not sure what this is, but we'll find out soon:
  provider: ^6.1.2

# (7): Specify necessary dependencies that are used in development:
dev_dependencies:

  # (7.1): Flutter Test: for unit testing
  flutter_test:

    # (7.1.1): ...
    sdk: flutter

  # (7.2): Linting for Flutter:
  # :: linting rules are in `analysis_options.yaml`
  flutter_lints: ^5.0.0

# :: some info on Dart here: https://dart.dev/tools/pub/pubspec

# (8): For Flutter-specific packages:
flutter:

  # (8.1): Requires usage of something called "Material Icons" font:
  uses-material-design: true

  # (8.2): Specify the list of assets for an application:
  # :: for "resolution-specific" information, see: https://flutter.dev/to/resolution-aware-images
  # :: for assets from other dependencies, see: https://flutter.dev/to/asset-from-package
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # (8.3): Specify a list of (custom) fonts below:
  # :: use the example format below, specifying "family" and "fonts" keys:
  # :: for info on fonts, see: https://flutter.dev/to/font-from-package
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700